[package]
name = "robotclipper-trans"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.4.0"
aws-sdk-mediaconvert = "1.27.0"
aws_lambda_events = "0.15.1"
lambda_runtime = "0.11.2"
serde = "1"
tokio = { version = "1", features = ["full"] }
