layer:
	wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz; \
    tar xvf ffmpeg-release-arm64-static.tar.xz; \
    mkdir -p ffmpeg/bin; \
    cp ffmpeg-6.1-arm64-static/ffmpeg ffmpeg/bin/; \
    cd ffmpeg; \
    zip -r ../ffmpeg.zip .
